version: "3.9"
services:
  postgres:
    container_name: postgres_container
    image: postgres:13.3
    command:
      - "postgres"
      - "-c"
      - "max_connections=10"
      - "-c"
      - "shared_buffers=128MB"
      - "-c"
      - "effective_cache_size=512MB"
      - "-c"
      - "work_mem=16MB"
      - "-c"
      - "maintenance_work_mem=512MB"
      - "-c"
      - "random_page_cost=1.1"
      - "-c"
      - "temp_file_limit=10GB"
      - "-c"
      - "log_min_duration_statement=200ms"
      - "-c"
      - "idle_in_transaction_session_timeout=10s"
      - "-c"
      - "lock_timeout=1s"
      - "-c"
      - "statement_timeout=60s"
      - "-c"
      - "shared_preload_libraries=pg_stat_statements"
      - "-c"
      - "pg_stat_statements.max=10000"
      - "-c"
      - "pg_stat_statements.track=all"
    environment:
      POSTGRES_DB: "mycalories_db"
      POSTGRES_USER: "mycalories_app"
      POSTGRES_PASSWORD: "calorie"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - /home/mykhailo/Documents/mycalories/:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mycalories_app -d mycalories_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 500M
    networks:
      - postgres


  tomcat:
    container_name: tomcat_container
    image: tomcat
    depends_on:
      - postgres
    environment:
      DATA_SOURCE_URI: "postgres"
    volumes:
      - /home/mykhailo/Documents/mycalories/logs/:/usr/local/tomcat/logs/
      - /home/mykhailo/Documents/ftp/files/target/MyCalories-0.0.1.war:/usr/local/tomcat/webapps-javaee/ROOT.war
    ports:
      - "8081:8080"
      - "8444:8443"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 300M
    networks:
      - postgres

networks:
  postgres:
    driver: bridge